---
abstract: 'Perl extension for checking data against the spamhaus blacklists'
author:
  - 'Wes Young, <wes@barely3am.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Abuse-Utils-Spamhaus
no_index:
  directory:
    - inc
    - t
requires:
  Net::DNS::Resolver: 0.67
  perl: 5.8.8
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
